# Generated by Django 5.2.6 on 2025-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('street_number', models.TextField(blank=True)),
                ('street_name', models.TextField(blank=True)),
                ('apartment_number', models.TextField(blank=True)),
                ('zip_code', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('party_affiliation', models.TextField(blank=True)),
                ('precinct', models.TextField(blank=True)),
            ],
        ),
    ]
