# Generated by Django 5.2.6 on 2025-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='v20state',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
