# Generated by Django 5.2.6 on 2025-10-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_v20state_voter_v21primary_voter_v21town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(blank=True),
        ),
    ]
